export default {
	REQUEST_RESET_FAILED: 'REQUEST_RESET_FAILED',
	REQUEST_RESET_ERROR: 'REQUEST_RESET_ERROR',
	REQUEST_RESET_SUCCESS: 'REQUEST_RESET_SUCCESS',
	RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
	RESET_PASSWORD_UNMATCH: 'RESET_PASSWORD_UNMATCH',
	RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
	RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
	RESET_PASSWORD_PENDING: 'RESET_PASSWORD_PENDING',
	REQUEST_RESET_PASSWORD_PENDING: 'REQUEST_RESET_PASSWORD_PENDING',
	VERIFY_PENDING: 'VERIFY_PENDING',
	VERIFY_SUCCESS: 'VERIFY_SUCCESS',
	VERIFY_ERROR: 'VERIFY_ERROR',
};
