const constants = {
	VERIFY_PENDING: 'VERIFY_PENDING',
	VERIFY_SUCCESS: 'VERIFY_SUCCESS',
	VERIFY_ERROR: 'VERIFY_ERROR',
	GETREQUEST_PENDING: 'GETREQUEST_PENDING',
	GETREQUEST_SUCCESS: 'GETREQUEST_SUCCESS',
	GETREQUEST_ERROR: 'GETREQUEST_ERROR',
};

export default constants;
